Add MediaPlayerSupportedFormat
esphome/aioesphomeapi pull request #925
Opened 2024-08-15 23:55 UTC by synesthesiam

Extends the media player info with a list of supported audio formats. This is used in Home Assistant to swap out media URLs going to the ESPHome device with proxy URLs that contain the converted audio.

See: https://github.com/home-assistant/core/pull/123254

2024-08-21 14:09 UTC, synesthesiam commented
@jesserockz Did I do something wrong to cause this test to fail?

2024-08-26 01:46 UTC, jesserockz commented
@synesthesiam I think you generated the files with a different proto version. Ill try fix

2024-08-26 01:51 UTC, jesserockz requested changes

2024-08-26 01:51 UTC, jesserockz commented on aioesphomeapi/model.py
> +                    x = {**x, "type": x["type_"]}
I don't think this is needed. It's only used on another message where there actually is a `type` field
```suggestion
```

2024-08-26 04:49 UTC, synesthesiam commented
> @synesthesiam I think you generated the files with a different proto version. Ill try fix

Ok, if not I'll try to upgrade and regenerate the files tomorrow.

2024-08-26 14:13 UTC, synesthesiam commented
@jesserockz I have libprotoc version 3.21.12. Is this too old? Too new?

2024-08-26 22:47 UTC, jesserockz commented
You can use docker to generate too
```bash
docker run -v "$PWD":/aioesphomeapi ghcr.io/esphome/aioesphomeapi-proto-builder:latest
```

2024-08-26 22:49 UTC, jesserockz approved these changes

2024-08-27 18:16 UTC, synesthesiam commented
Do I need to add a version bump too?

2024-08-27 23:26 UTC, merged